backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"  # Folder where uploaded images go
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
