backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "products"
    label: "Products"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "price", label: "Price", widget: "string" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "link", label: "Amazon Link", widget: "string" }
