backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Product Cards"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Product Name", name: "title", widget: "string" }
      - { label: "Amazon Link", name: "link", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Product Image", name: "image", widget: "image" }
      - { label: "Category", name: "category", widget: "select", options: ["electronics", "clothing", "home", "other"] }
